export default

[
  {
    "nombre": "El código Da Vinci",
    "autor": "Dan Brown",
    "paginas": 425,
    "sinopsis": "El profesor Robert Langdon es llamado para resolver un misterio detrás de un asesinato en el Museo del Louvre, lo que lo lleva a una conspiración que data de siglos.",
    "puntuacion": 4.3,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2003,
    "portada":"https://www.planetadelibros.com.pe/usuaris/libros/fotos/251/m_libros/250723_portada_el-codigo-da-vinci_dan-brown_201611091752.jpg",
    "subcategorias": ["Ficción histórica", "Thriller"]
  },
  {
    "nombre": "La chica del tren",
    "autor": "Paula Hawkins",
    "paginas": 250,
    "sinopsis": "Rachel, una mujer devastada por su vida personal, se obsesiona con una pareja que ve todos los días desde el tren, hasta que una desaparición la involucra en un misterio oscuro.",
    "puntuacion": 4.1,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2015,
    "portada":"https://images.cdn2.buscalibre.com/fit-in/360x360/a9/dd/a9dd9755bde59005eb4421bb1f061bcc.jpg",
    "subcategorias": ["Suspenso psicológico", "Thriller"]
  },
  {
    "nombre": "Perdida",
    "autor": "Gillian Flynn",
    "paginas": 398,
    "sinopsis": "Nick Dunne se convierte en el principal sospechoso cuando su esposa Amy desaparece misteriosamente el día de su quinto aniversario.",
    "puntuacion": 4.4,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2012,
    "portada":"https://images.cdn1.buscalibre.com/fit-in/360x360/01/b5/01b500597d555ef79a1b6e443ca3a0de.jpg",
    "subcategorias": ["Thriller psicológico", "Suspenso"]
  },
  {
    "nombre": "El silencio de los corderos",
    "autor": "Thomas Harris",
    "paginas": 298,
    "sinopsis": "Clarice Starling, una joven agente del FBI, busca la ayuda del peligroso Dr. Hannibal Lecter para capturar a un asesino en serie.",
    "puntuacion": 4.6,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1988,
    "portada":"https://images.cdn3.buscalibre.com/fit-in/360x360/46/6b/466b61298129d120cc99189338a50c18.jpg",
    "subcategorias": ["thriller_psicológico", "crimen"]
  },
  {
    "nombre": "Sherlock Holmes: Estudio en escarlata",
    "autor": "Arthur Conan Doyle",
    "paginas": 102,
    "sinopsis": "El detective Sherlock Holmes y su compañero, el Dr. Watson, investigan el misterioso asesinato de un hombre, lo que los lleva a descubrir una conspiración oculta.",
    "puntuacion": 4.6,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1887,
    "portada":"https://www.planetadelibros.com.pe/usuaris/libros/fotos/349/m_libros/348874_portada_estudio-en-escarlata_arthur-conan-doyle_202203180959.jpg",
    "subcategorias": ["detectivesco", "ficción_clásica"]
  },
  {
    "nombre": "La verdad sobre el caso Harry Quebert",
    "autor": "Joël Dicker",
    "paginas": 68,
    "sinopsis": "Un escritor joven investiga el caso de su mentor, acusado de asesinato, desenterrando secretos oscuros en una pequeña ciudad estadounidense.",
    "puntuacion": 4.2,
    "idioma_original": "Francés",
    "año_lanzamiento": 2012,
    "portada":"https://images.cdn3.buscalibre.com/fit-in/360x360/fe/e1/fee1e9c818cc41dfc3ca68e4175da9ec.jpg",
    "subcategorias": ["suspenso", "ficción_contemporánea"]
  },
  {
    "nombre": "Asesinato en el Orient Express",
    "autor": "Agatha Christie",
    "paginas": 176,
    "sinopsis": "El detective Hércules Poirot investiga el asesinato de un pasajero en el lujoso tren Orient Express, donde todos los viajeros son sospechosos.",
    "puntuacion": 4.4,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1934,
    "portada":"https://images.cdn1.buscalibre.com/fit-in/360x360/2f/e4/2fe487d9fe7072bfc1a4f419964b0c0a.jpg",
    "subcategorias": ["detectivesco", "crimen"]
  },
  {
    "nombre": "La sombra del viento",
    "autor": "Carlos Ruiz Zafón",
    "paginas": 288,
    "sinopsis": "Daniel Sempere descubre un libro maldito en un misterioso cementerio de libros olvidados, lo que lo envuelve en un oscuro enigma que afecta su vida y la de quienes lo rodean.",
    "puntuacion": 4.6,
    "idioma_original": "Español",
    "año_lanzamiento": 2001,
    "portada":"https://images.cdn2.buscalibre.com/fit-in/360x360/c0/0d/c00dd3a9668387339be2de5e97bb589c.jpg",
    "subcategorias": ["ficción_histórica", "Novela_gótica"]
  },
  {
    "nombre": "El psicoanalista",
    "autor": "John Katzenbach",
    "paginas": 379,
    "sinopsis": "El doctor Frederick Starks, un psicoanalista de Nueva York, recibe una carta anónima que lo amenaza con destruir su vida si no descubre la identidad del remitente.",
    "puntuacion": 4.3,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2002,
    "portada": "https://cdn.prod.website-files.com/63b0bef93fcbb004e753f1ce/65184724c76062db75245d0b_el-psicoanalista.jpeg",
    "subcategorias": ["Thriller_psicológico", "Suspenso"]
  },
  {
    "nombre": "El club Dumas",
    "autor": "Arturo Pérez-Reverte",
    "paginas": 480,
    "sinopsis": "Lucas Corso, un cazador de libros raros, se ve envuelto en un misterioso complot relacionado con un manuscrito perdido de Alejandro Dumas y un misterioso libro de demonología.",
    "puntuacion": 4.2,
    "idioma_original": "Español",
    "año_lanzamiento": 1993,
    "portada": "https://www.penguinlibros.com/pe/2538855/el-club-dumas.jpg",
    "subcategorias": ["suspenso", "ficción_literaria"]
  },
  {
    "nombre": "El guardián invisible",
    "autor": "Dolores Redondo",
    "paginas": 1275,
    "sinopsis": "La inspectora Amaia Salazar investiga una serie de asesinatos de adolescentes en el Valle de Baztán, donde leyendas locales y misterios familiares se entrelazan.",
    "puntuacion": 4.1,
    "idioma_original": "Español",
    "año_lanzamiento": 2013,
    "portada": "https://images.cdn2.buscalibre.com/fit-in/360x360/d1/8c/d18c8041cdbe2be5dcd378a24b426465.jpg",
    "subcategorias": ["crimen", "ficción_policíaca"]
  },
  {
    "nombre": "It (ESO)",
    "autor": "Stephen King",
    "paginas": 2332,
    "sinopsis": "Cuenta la historia, en un juego de correspondencias con el pasado y el presente, de un grupo de siete amigos que son perseguidos por una entidad sobrenatural, al que llaman «Eso», que es capaz de cambiar de forma y se alimenta principalmente del terror que produce en sus víctimas.",
    "puntuacion": 4.2,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1986,
    "portada": "https://images.cdn1.buscalibre.com/fit-in/360x360/03/0a/030a419b5cbfda84843b6b9fdc5d8273.jpg",
    "subcategorias": ["suspenso"]
  },
  {
    "nombre": "La verdad sobre el caso Savolta",
    "autor": "Eduardo Mendoza",
    "paginas": 229,
    "sinopsis": "En Barcelona de principios del siglo XX, un joven abogado se ve envuelto en una trama de conspiraciones, asesinatos y corrupción industrial.",
    "puntuacion": 4.3,
    "idioma_original": "Español",
    "año_lanzamiento": 1975,
    "portada":"https://www.planetadelibros.com.pe/usuaris/libros/fotos/201/m_libros/200372_portada_la-verdad-sobre-el-caso-savolta_eduardo-mendoza_201505261015.jpg",
    "subcategorias": ["ficción_histórica", "crimen"]
  },
  {
    "nombre": "La mujer en la ventana",
    "autor": "A.J. Finn",
    "paginas": 303,
    "sinopsis": "Anna Fox, una mujer que sufre de agorafobia, cree haber presenciado un crimen desde la ventana de su casa, pero nadie le cree.",
    "puntuacion": 4.0,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2018,
    "portada":"https://www.penguinlibros.com/pe/1678326/la-mujer-en-la-ventana.jpg",
    "subcategorias": ["thriller_psicológico", "suspenso"]
  },
  {
    "nombre": "La casa al final de Needless Street",
    "autor": "Catriona Ward",
    "paginas": 352,
    "sinopsis": "Un hombre solitario, una niña desaparecida y una casa llena de secretos son los elementos de un misterioso rompecabezas lleno de giros inesperados.",
    "puntuacion": 4.3,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2021,
    "portada":"https://http2.mlstatic.com/D_NQ_NP_835909-MLA48734198860_012022-O.webp",
    "subcategorias": ["suspenso_psicológico"]
  },
  {
    "nombre": "Un cadáver en la biblioteca",
    "autor": "Agatha Christie",
    "paginas": 144,
    "sinopsis": "Miss Marple investiga el caso de un cadáver encontrado en la biblioteca de la familia Bantry, en lo que parece ser un asesinato lleno de intrigas.",
    "puntuacion": 4.2,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1942,
    "portada":"https://images.cdn3.buscalibre.com/fit-in/360x360/89/5a/895a73a21118fdbda9a68b605933f912.jpg",
    "subcategorias": ["detectivesco", "crimen"]
  },
  {
    "nombre": "Narraciones Extraordinarias",
    "autor": "Edgar Allan Poe",
    "paginas": 126,
    "sinopsis": "En la selección que presenta esta edición, Poe perfila, en un alarde de dominio de la creación de atmósferas, la psicología de personajes angustiados por las pesadillas, las fantasías y temores que, sin duda, preludian las contradicciones del ser humano contemporáneo. La mayoría de estas narraciones están dominadas por el terror y la presencia de lo sobrenatural. Una lectura que es una invitación abierta a sumergirse en el extraordinario universo de un creador que parece pasearse con gracia y elegancia en los temas más inquietantes y escalofriantes de la naturaleza humana.",
    "puntuacion": 4.4,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2006,
    "portada":"https://cdn.prod.website-files.com/6034d7d1f3e0f52c50b2adee/625452cdb2e075d6ee11f565_6034d7d1f3e0f59d7cb2b343_Narraciones-extraordinarias-edgar-allan-poe-editorial-alma-pocket.jpeg",
    "subcategorias": ["cuentos_cortos"]
  },
  {
    "nombre": "El nombre de la rosa",
    "autor": "Umberto Eco",
    "paginas": 424,
    "sinopsis": "En una abadía medieval, un monje y su joven discípulo investigan una serie de misteriosas muertes que parecen estar conectadas con un libro prohibido.",
    "puntuacion": 4.5,
    "idioma_original": "Italiano",
    "año_lanzamiento": 1980,
    "portada":"https://images.cdn1.buscalibre.com/fit-in/360x360/df/71/df71760154e720c45c277c429f58bbba.jpg",
    "subcategorias": ["ficción_histórica", "filosofía"]
  },
  {
    "nombre": "Coraline",
    "autor": "Neil Gaiman",
    "paginas": 98,
    "sinopsis": "Coraline Jones es una niña que se muda a una antigua casa con sus padres. Un día, descubre una puerta secreta que la lleva a un mundo alternativo donde todo parece mejor, pero pronto se da cuenta de que este mundo es una trampa creada por una entidad maligna que pretende reemplazar a su madre con una versión de botones. Coraline debe enfrentarse a sus miedos y salvar a sus padres en el proceso.",
    "puntuacion": 4.5,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2002,
    "portada": "https://images.cdn1.buscalibre.com/fit-in/360x360/0b/a9/0ba9cadc466f5329d6abf5a68d76cd1a.jpg",
    "subcategorias": ["ficción_juvenil"]
  },
  {
    "nombre": "El hombre de tiza",
    "autor": "C.J. Tudor",
    "paginas": 232,
    "sinopsis": "Un grupo de amigos encuentra el cadáver de una niña después de seguir un rastro de dibujos en tiza, desatando una serie de eventos aterradores que los persiguen hasta la adultez.",
    "puntuacion": 4.2,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2018,
    "portada":"https://images.cdn3.buscalibre.com/fit-in/360x360/9a/c6/9ac6b2eff7aad879312dc148910df744.jpg",
    "subcategorias": ["thriller_psicológico", "suspenso"]
  },
  {
    "nombre": "El cuarto mono",
    "autor": "J.D. Barker",
    "paginas": 528,
    "sinopsis": "Un asesino en serie apodado 'El Cuarto Mono' ha eludido a la policía durante años, pero cuando su cuerpo es encontrado, comienza una carrera contra el tiempo para salvar a su última víctima.",
    "puntuacion": 4.4,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2017,
    "portada":"https://m.media-amazon.com/images/I/8141Tj7qnwL._AC_UF894,1000_QL80_.jpg",
    "subcategorias": ["thriller", "crimen"]
  },
  {
    "nombre": "El hombre que perseguía su sombra",
    "autor": "David Lagercrantz",
    "paginas": 400,
    "sinopsis": "Lisbeth Salander y Mikael Blomkvist se enfrentan a un nuevo misterio vinculado a un programa secreto de experimentos humanos.",
    "puntuacion": 4.1,
    "idioma_original": "Sueco",
    "año_lanzamiento": 2017,
    "portada":"https://www.planetadelibros.com.pe/usuaris/libros/fotos/260/m_libros/259819_portada_el-hombre-que-perseguia-su-sombra_david-lagercrantz_201709071550.jpg",
    "subcategorias": ["suspenso", "ficción_contemporánea"]
  },
  {
    "nombre": "El jardín de bronce",
    "autor": "Gustavo Malajovich",
    "paginas": 576,
    "sinopsis": "Un arquitecto argentino busca desesperadamente a su hija desaparecida, lo que lo lleva a descubrir una red de corrupción y secuestros.",
    "puntuacion": 4.3,
    "idioma_original": "Español",
    "año_lanzamiento": 2012,
    "portada":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiS5PnRi2Gt_drUgARvSpP_3MwBBmP4V-D2w&s",
    "subcategorias": ["thriller", "crimen"]
  },
  {
    "nombre": "El libro de los muertos",
    "autor": "Douglas Preston y Lincoln Child",
    "paginas": 621,
    "sinopsis": "El agente especial Pendergast intenta resolver el misterio de una serie de asesinatos mientras su propio hermano, un criminal, juega un peligroso juego con él.",
    "puntuacion": 4.2,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2006,
    "portada":"https://images.cdn2.buscalibre.com/fit-in/360x360/c8/6e/c86e1cfd13ab4f7fc1041d76cc876a1f.jpg",
    "subcategorias": ["suspenso", "ficción_histórica"]
  },
  {
    "nombre": "La casa torcida",
    "autor": "Agatha Christie",
    "paginas": 272,
    "sinopsis": "En una mansión inglesa, la rica y poderosa familia Leonides es sacudida por el asesinato del patriarca, y todos los miembros de la familia son sospechosos.",
    "puntuacion": 4.3,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1949,
    "portada":"https://images.cdn3.buscalibre.com/fit-in/360x360/17/8c/178c6352e8f3de407ee2d141dad3025b.jpg",
    "subcategorias": ["crimen", "detectivesco"]
  },
  {
    "nombre": "La desaparición de Stephanie Mailer",
    "autor": "Joël Dicker",
    "paginas": 656,
    "sinopsis": "Veinte años después de que se resolviera un caso de asesinato múltiple, una periodista desaparece mientras investigaba lo que realmente sucedió aquella noche.",
    "puntuacion": 4.1,
    "idioma_original": "Francés",
    "año_lanzamiento": 2018,
    "portada":"https://images.cdn2.buscalibre.com/fit-in/520x520/55/88/558835f98368c545281ea2ac875271b1.jpg",
    "subcategorias": ["thriller", "suspenso_psicológico"]
  },
  {
    "nombre": "La sustancia del mal",
    "autor": "Luca D'Andrea",
    "paginas": 432,
    "sinopsis": "Un documentalista investiga un triple asesinato ocurrido en los Alpes italianos en 1985, descubriendo secretos perturbadores sobre la comunidad local.",
    "puntuacion": 4.0,
    "idioma_original": "Italiano",
    "año_lanzamiento": 2016,
    "portada":"https://images.cdn2.buscalibre.com/fit-in/360x360/39/63/3963da43008b802018c71c342a12e9a3.jpg",
    "subcategorias": ["thriller_psicológico", "crimen"]
  },
  {
    "nombre": "El ángel caído",
    "autor": "Daniel Silva",
    "paginas": 496,
    "sinopsis": "El restaurador de arte y espía Gabriel Allon investiga una red de tráfico de arte y asesinato vinculada al Vaticano y al Medio Oriente.",
    "puntuacion": 4.4,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2012,
    "portada":"https://archive.org/services/img/fallenangel0000silv_l3w5/full/pct:200/0/default.jpg",
    "subcategorias": ["thriller", "ficcion_historica"]
  },
  {
    "nombre": "El asesinato de Roger Ackroyd",
    "autor": "Agatha Christie",
    "paginas": 320,
    "sinopsis": "El detective Hércules Poirot investiga el asesinato del acaudalado Roger Ackroyd en una pequeña villa, revelando un final sorprendente e innovador.",
    "puntuacion": 4.6,
    "idioma_original": "Inglés",
    "año_lanzamiento": 1926,
    "portada":"https://images.cdn1.buscalibre.com/fit-in/360x360/8a/a0/8aa0663099c54df6d7c1ba010d656ea8.jpg",
    "subcategorias": ["crimen", "detectivesco"]
  },
  {
    "nombre": "La paciente silenciosa",
    "autor": "Alex Michaelides",
    "paginas": 384,
    "sinopsis": "Alicia Berenson, una famosa pintora, es encontrada junto al cadáver de su esposo con una pistola en la mano. Desde ese momento, permanece en silencio, sin decir una sola palabra, hasta que Theo Faber, un psicoterapeuta, se obsesiona con desentrañar su caso y descubrir la verdad detrás de su silencio.",
    "puntuacion": 4.2,
    "idioma_original": "Inglés",
    "año_lanzamiento": 2019,
    "portada":"https://www.penguinlibros.com/pe/1667679-large_default/la-paciente-silenciosa.webp",
    "subcategorias": ["thriller_psicológico", "suspenso"]
  }
]